version: '3.1'
services:
   db:
     image: mysql:5.7
     secrets:
      - dbdevrootpasswd
      - dbdevpasswd
     environment:
       MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/dbdevrootpasswd"
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: "/run/secrets/dbdevpasswd"
     volumes:
      - wpsecret2:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]
       restart_policy:
         condition: any

   wordpress:
     image: wordpress:latest
     ports:
       - "80:80"
     depends_on:
       - db
     secrets:
       - source: "dbdevpasswd"
         target: "wpdbpaswd"
         uid: "0"
         gid: "0"
         mode: 0444
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_DATABASE: wordpress
       WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/wpdbpaswd"
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == worker]
       restart_policy:
         condition: on-failure

volumes:
  wpsecret2:
    external: true


secrets:
  dbdevrootpasswd:
    external:
      name: "de_dbdevrootpasswd"

secrets:
  dbdevpasswd:
    external:
      name: "de_dbdevpasswd"
